[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "emulator"
doctest = false

[[bin]]
name = "emulator"
test = false
doctest = false

[dependencies]
