name: 8080-cpu-emulator-rust-build

on:
  push:
    branches: [ "8080-emulator" ]
  pull_request:
    branches: [ "8080-emulator" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Run cpu diagnosis
      run: cargo run --features="bdos_mock"
    - name: Install targets
      run: rustup target add aarch64-apple-ios aarch64-apple-darwin x86_64-apple-darwin
    - name: Build for x86_64 macOS
      run: cargo build --lib --target=x86_64-apple-darwin --release --verbose
    - name: Build for Apple Silicon macOS
      run: cargo build --lib --target=aarch64-apple-darwin --release --verbose
    - name: Build for iOS
      run: cargo build --lib --target=aarch64-apple-ios --release --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: x86_64_darwin
        path: target/x86_64-apple-darwin/release/libi8080emulator.a
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64_darwin
        path: target/aarch64-apple-darwin/release/libi8080emulator.a
    - uses: actions/upload-artifact@v3
      with:
        name: iOS
        path: target/aarch64-apple-ios/release/libi8080emulator.a
